#!/usr/bin/env python3
"""Builds tr/index.html (static Turkish page, indexable by search engines) from index.html.

UI strings come from the `tr` block in js/app.js, so only the head/SEO texts live here.
Re-run after every change to index.html or the translations: python3 tools/make_tr_page.py
"""
import html, json, os, re

ROOT = os.path.join(os.path.dirname(__file__), '..')
BASE = 'https://numericworks.github.io/GcodeScope/'


def read(p):
    with open(os.path.join(ROOT, p), encoding='utf-8') as f:
        return f.read()


def tr_strings():
    js = read('js/app.js')
    block = js[js.index('\n  tr: {'):]
    block = block[:block.index('\n  },')]
    return {k: v.replace("\\'", "'") for k, v in re.findall(r"(\w+): '((?:[^'\\]|\\.)*)'", block)}


def sub(s, old, new, count=1):
    if s.count(old) != count:
        raise SystemExit(f'expected {count}× {old!r} in index.html, found {s.count(old)}')
    return s.replace(old, new)


def main():
    T = tr_strings()
    s = read('index.html')

    # ---- head
    s = sub(s, '<html lang="en">', '<html lang="tr">')
    s = re.sub(r'<title>.*?</title>',
               '<title>GcodeScope — Ücretsiz Online G-code Görüntüleyici (CNC ve 3D Baskı) | NumericWorks</title>', s)
    desc = ('Tarayıcında çalışan ücretsiz ve gizli G-code görüntüleyici. .gcode veya .nc dosyasını bırak; '
            '3D takım yolunu, katmanları, hızlı hareketleri, boyutu, baskı süresini ve filamenti gör. '
            'Dosyan yüklenmez, telefonda da çalışır.')
    s = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{desc}">', s)
    s = sub(s, f'<link rel="canonical" href="{BASE}">', f'<link rel="canonical" href="{BASE}tr/">')
    s = sub(s, f'<meta property="og:url" content="{BASE}">', f'<meta property="og:url" content="{BASE}tr/">')
    s = re.sub(r'<meta property="og:title" content="[^"]*">',
               '<meta property="og:title" content="GcodeScope — Ücretsiz G-code Görüntüleyici (CNC ve 3D baskı)">', s)
    s = re.sub(r'<meta property="og:description" content="[^"]*">',
               '<meta property="og:description" content=".gcode / .nc dosyasını bırak, takım yolunu 3D gör. '
               'Tamamen tarayıcında çalışır — dosyan cihazından çıkmaz.">', s)
    s = re.sub(r'<meta property="og:image:alt" content="[^"]*">',
               '<meta property="og:image:alt" content="GcodeScope ile bir G-code dosyasının 3D takım yolu önizlemesi">', s)
    s = sub(s, '<meta property="og:locale" content="en_US">', '<meta property="og:locale" content="tr_TR">')
    s = sub(s, '<meta property="og:locale:alternate" content="tr_TR">', '<meta property="og:locale:alternate" content="en_US">')
    s = re.sub(r'  <script>\n    // Visitors who explicitly picked Turkish.*?</script>\n', '', s, flags=re.S)
    s = re.sub(r'<script type="application/ld\+json">.*?</script>',
               lambda _: '<script type="application/ld+json">\n' + ld_json(T) + '\n  </script>', s, flags=re.S)

    # ---- relative paths (page lives one folder deeper)
    for a in ('href="assets/', 'src="assets/', 'href="css/', 'src="js/', 'data-sample="samples/'):
        s = s.replace(a, a.replace('="', '="../'))
    s = sub(s, '"./vendor/three.module.min.js", "three/addons/": "./vendor/"',
            '"../vendor/three.module.min.js", "three/addons/": "../vendor/"')
    s = sub(s, '<a class="brand" href="./" aria-label="GcodeScope home">',
            '<a class="brand" href="./" aria-label="GcodeScope ana sayfa">')
    s = sub(s, '<a href="./" hreflang="en" lang="en" data-lang="en" aria-current="page">EN</a>',
            '<a href="../" hreflang="en" lang="en" data-lang="en">EN</a>')
    s = sub(s, '<a href="tr/" hreflang="tr" lang="tr" data-lang="tr">TR</a>',
            '<a href="./" hreflang="tr" lang="tr" data-lang="tr" aria-current="page">TR</a>')
    s = sub(s, 'aria-label="Language"', 'aria-label="Dil"')

    # ---- visible text: static Turkish so crawlers see it without running JS
    def repl(m):
        key = m.group(2)
        if key not in T:
            raise SystemExit(f'missing tr translation: {key}')
        return f'{m.group(1)}{html.escape(T[key], quote=False)}{m.group(3)}'
    s = re.sub(r'(<[^>]*\bdata-i18n="([^"]+)"[^>]*>)[^<]*(</)', repl, s)
    os.makedirs(os.path.join(ROOT, 'tr'), exist_ok=True)
    with open(os.path.join(ROOT, 'tr', 'index.html'), 'w', encoding='utf-8') as f:
        f.write(s.replace('<head>', '<head>\n  <!-- Generated by tools/make_tr_page.py from index.html; do not edit by hand. -->', 1))
    print('wrote tr/index.html')


def ld_json(T):
    data = {
        '@context': 'https://schema.org',
        '@graph': [
            {
                '@type': 'WebApplication',
                'name': 'GcodeScope',
                'url': BASE + 'tr/',
                'description': 'Tarayıcında çalışan ücretsiz ve gizli G-code görüntüleyici. 3D baskı ve CNC dosyaları '
                               'için 3D takım yolunu, katmanları, hızlı hareketleri, boyutu, baskı süresini ve filamenti gösterir.',
                'applicationCategory': 'DesignApplication',
                'operatingSystem': 'Any (web browser)',
                'browserRequirements': 'Requires JavaScript and WebGL',
                'inLanguage': 'tr',
                'isAccessibleForFree': True,
                'offers': {'@type': 'Offer', 'price': '0', 'priceCurrency': 'USD'},
                'image': BASE + 'assets/og-image.png',
                'publisher': {'@type': 'Organization', 'name': 'NumericWorks'},
            },
            {
                '@type': 'FAQPage',
                'mainEntity': [
                    {'@type': 'Question', 'name': T[f'faq{i}q'],
                     'acceptedAnswer': {'@type': 'Answer', 'text': T[f'faq{i}a']}}
                    for i in (1, 2, 3)
                ],
            },
        ],
    }
    return '\n'.join('  ' + l for l in json.dumps(data, ensure_ascii=False, indent=2).split('\n'))


if __name__ == '__main__':
    main()
