#!/usr/bin/env python3
"""Generates the small demo files in /samples. Run: python3 tools/make_samples.py"""
import math, os

OUT = os.path.join(os.path.dirname(__file__), '..', 'samples')

def f(v): return f"{v:.3f}".rstrip('0').rstrip('.')

def print_sample():
    L = []
    w = L.append
    w('; generated by GcodeScope sample generator (PrusaSlicer-style comments)')
    w('M82 ; absolute extrusion'); w('G21'); w('G90'); w('M104 S210'); w('M140 S60'); w('G28')
    w('G92 E0'); w('G1 Z0.2 F3000'); w('G1 X10 Y10 F6000')
    w('G1 X10 Y100 E12 F1200 ; purge line'); w('G92 E0')
    e = 0.0
    cx, cy = 110, 110
    lh, layers, N = 0.2, 80, 48
    area = 0.42 * lh  # mm^2 of bead
    fil_area = math.pi * 0.875 ** 2
    def shape(t, a, inset):
        # rounded square that twists and bulges with height
        r = 18 + 4 * math.sin(t * math.pi) - inset
        k = 4
        c, s = math.cos(a), math.sin(a)
        rr = r / (abs(c) ** k + abs(s) ** k) ** (1 / k)
        tw = t * math.pi / 3
        return cx + rr * math.cos(a + tw), cy + rr * math.sin(a + tw)
    for li in range(layers):
        z = lh * (li + 1)
        t = li / (layers - 1)
        w(f';LAYER_CHANGE'); w(f';Z:{f(z)}')
        w(f'G1 Z{f(z + 0.4)} F3000'); 
        x0, y0 = shape(t, 0, 0)
        w(f'G0 X{f(x0)} Y{f(y0)} F9000'); w(f'G1 Z{f(z)} F3000')
        w('G1 E{:.5f} F2400'.format(e + 0.8)); e += 0.8  # unretract
        for inset in (0, 0.45):
            px, py = shape(t, 0, inset)
            w(f'G1 X{f(px)} Y{f(py)} F1800')
            for i in range(1, N + 1):
                a = 2 * math.pi * i / N
                nx, ny = shape(t, a, inset)
                d = math.hypot(nx - px, ny - py)
                e += d * area / fil_area
                w(f'G1 X{f(nx)} Y{f(ny)} E{e:.5f}')
                px, py = nx, ny
        if li < 3 or li >= layers - 3:
            # solid-ish diagonal infill on bottom/top layers
            rng = 15
            for j, off in enumerate(range(-rng, rng + 1, 3)):
                ax, ay = cx + off - 10, cy - 10 + (j % 2) * 20
                bx, by = cx + off + 10, cy + 10 - (j % 2) * 20
                if li % 2: ax, ay, bx, by = ay - cy + cx, ax - cx + cy, by - cy + cx, bx - cx + cy
                w(f'G0 X{f(ax)} Y{f(ay)} F9000')
                e += math.hypot(bx - ax, by - ay) * area / fil_area
                w(f'G1 X{f(bx)} Y{f(by)} E{e:.5f} F2400')
        w('G1 E{:.5f} F2400'.format(e - 0.8)); e -= 0.8  # retract
    w(f'G1 Z{f(lh * layers + 10)} F3000'); w('M104 S0'); w('M140 S0'); w('M84')
    fil_mm = e + 12
    w(f'; filament used [mm] = {fil_mm:.2f}')
    w(f'; filament used [g] = {fil_mm * fil_area * 1.24 / 1000:.2f}')
    w('; estimated printing time (normal mode) = 42m 18s')
    w('; filament_type = PLA')
    return '\n'.join(L) + '\n'

def cnc_sample():
    L = []
    w = L.append
    w('%'); w('O1001 (GCODESCOPE DEMO PLATE)')
    w('(MATERIAL: ALUMINUM 6061, STOCK 100 X 70 X 12)')
    w('G21 G90 G17 G40 G49 G80')
    # T1 contour with rounded corners, 3 step-downs
    w('T1 M06 (10MM FLAT END MILL)'); w('S8000 M03'); w('G54'); w('G43 H01 Z25.'); w('M08')
    R = 8
    x0, y0, x1, y1 = -5, -5, 105, 75
    # lead-in: G41 line + tangent arc, lead-out: tangent arc + G40 line
    w(f'G00 X{x0 - 15} Y{y0 + R - 5}')
    for z in (-3, -6, -9):
        w(f'G00 Z2.'); w(f'G01 Z{z}. F300')
        w(f'G41 D01 G01 X{x0 - 5} Y{y0 + R - 5} F1200')
        w(f'G03 X{x0} Y{y0 + R} I0. J5.')
        w(f'G01 Y{y1 - R}'); w(f'G02 X{x0 + R} Y{y1} I{R} J0.')
        w(f'G01 X{x1 - R}'); w(f'G02 X{x1} Y{y1 - R} I0. J-{R}.')
        w(f'G01 Y{y0 + R}'); w(f'G02 X{x1 - R} Y{y0} I-{R}. J0.')
        w(f'G01 X{x0 + R}'); w(f'G02 X{x0} Y{y0 + R} R{R}.')
        w(f'G03 X{x0 - 5} Y{y0 + R + 5} I-5. J0.')
        w(f'G40 G01 X{x0 - 15}')
        w(f'G00 Y{y0 + R - 5}')
    w('G00 Z25.')
    # circular pocket with helical entry, R50 center 30,35 radius 15
    w('(CIRCULAR POCKET D30)')
    cx, cy = 30, 35
    w(f'G00 X{cx + 3} Y{cy}'); w('G00 Z2.'); w('G01 Z0. F300')
    for i in range(4):
        w(f'G03 X{cx + 3} Y{cy} Z{-1.5 * (i + 1)} I-3. J0. F600')
    for r in (6, 9, 12, 10):
        w(f'G01 X{cx + r} Y{cy} F1000'); w(f'G03 X{cx + r} Y{cy} I-{r}. J0.')
    w('G00 Z25.')
    # slot with arcs
    w('(SLOT)')
    w('G00 X60. Y20.'); w('G00 Z2.'); w('G01 Z-2. F300')
    w('G01 X80. F1000'); w('G03 X80. Y50. R15.'); w('G01 X60.'); w('G03 X60. Y20. R15.')
    w('G00 Z25.'); w('M09'); w('M05')
    # T3 spot drill, T2 peck drill, T4 tap, T1 bore milling
    w('T3 M06 (SPOT DRILL D10 90DEG)'); w('S3000 M03'); w('G43 H03 Z25.'); w('M08')
    w('G00 X5. Y5.')
    w('G99 G81 X5. Y5. Z-1.5 R2. F150')
    w('X95.'); w('Y65.'); w('X5.')
    w('G80'); w('G00 Z25.')
    w('T2 M06 (6.8MM DRILL)'); w('S3500 M03'); w('G43 H02 Z25.'); w('M08')
    w('G00 X5. Y5.')
    w('G98 G83 X5. Y5. Z-14. R2. Q4. F250')
    w('X95.'); w('Y65.'); w('X5.')
    w('G80'); w('G00 Z25.')
    w('T4 M06 (TAP M8X1.25)'); w('S400 M03'); w('G43 H04 Z25.')
    w('M29 S400')
    w('G99 G84 X95. Y5. Z-12. R5. F500')
    w('Y65.')
    w('G80'); w('G00 Z25.')
    w('T1 M06 (10MM FLAT END MILL)'); w('S8000 M03'); w('G43 H01 Z25.')
    w('(BORE MILLING D16)')
    w('G00 X45. Y60.'); w('G00 Z2.'); w('G01 Z0. F300'); w('G01 X48. F800')
    for i in range(1, 5):
        w(f'G03 X48. Y60. Z-{i * 2}. I-3. J0.')
    w('G03 X48. Y60. I-3. J0.'); w('G01 X45.')
    w('G00 Z50.'); w('M09'); w('M05')
    w('G28 G91 Z0.'); w('G90'); w('M30'); w('%')
    return '\n'.join(L) + '\n'

os.makedirs(OUT, exist_ok=True)
open(os.path.join(OUT, 'sample-print.gcode'), 'w').write(print_sample())
open(os.path.join(OUT, 'sample-cnc.nc'), 'w').write(cnc_sample())
print('ok')
