#!/usr/bin/env python3
"""Generates the small demo files in /samples. Run: python3 tools/make_samples.py"""
import math, os

OUT = os.path.join(os.path.dirname(__file__), '..', 'samples')

def f(v): return f"{v:.3f}".rstrip('0').rstrip('.')

def print_sample():
    L = []
    w = L.append
    w('; generated by GcodeScope sample generator (PrusaSlicer-style comments)')
    w('M82 ; absolute extrusion'); w('G21'); w('G90'); w('M104 S210'); w('M140 S60'); w('G28')
    w('G92 E0'); w('G1 Z0.2 F3000'); w('G1 X10 Y10 F6000')
    w('G1 X10 Y100 E12 F1200 ; purge line'); w('G92 E0')
    e = 0.0
    cx, cy = 110, 110
    lh, layers, N = 0.2, 80, 48
    area = 0.42 * lh  # mm^2 of bead
    fil_area = math.pi * 0.875 ** 2
    def shape(t, a, inset):
        # rounded square that twists and bulges with height
        r = 18 + 4 * math.sin(t * math.pi) - inset
        k = 4
        c, s = math.cos(a), math.sin(a)
        rr = r / (abs(c) ** k + abs(s) ** k) ** (1 / k)
        tw = t * math.pi / 3
        return cx + rr * math.cos(a + tw), cy + rr * math.sin(a + tw)
    for li in range(layers):
        z = lh * (li + 1)
        t = li / (layers - 1)
        w(f';LAYER_CHANGE'); w(f';Z:{f(z)}')
        w(f'G1 Z{f(z + 0.4)} F3000'); 
        x0, y0 = shape(t, 0, 0)
        w(f'G0 X{f(x0)} Y{f(y0)} F9000'); w(f'G1 Z{f(z)} F3000')
        w('G1 E{:.5f} F2400'.format(e + 0.8)); e += 0.8  # unretract
        for inset in (0, 0.45):
            px, py = shape(t, 0, inset)
            w(f'G1 X{f(px)} Y{f(py)} F1800')
            for i in range(1, N + 1):
                a = 2 * math.pi * i / N
                nx, ny = shape(t, a, inset)
                d = math.hypot(nx - px, ny - py)
                e += d * area / fil_area
                w(f'G1 X{f(nx)} Y{f(ny)} E{e:.5f}')
                px, py = nx, ny
        if li < 3 or li >= layers - 3:
            # solid-ish diagonal infill on bottom/top layers
            rng = 15
            for j, off in enumerate(range(-rng, rng + 1, 3)):
                ax, ay = cx + off - 10, cy - 10 + (j % 2) * 20
                bx, by = cx + off + 10, cy + 10 - (j % 2) * 20
                if li % 2: ax, ay, bx, by = ay - cy + cx, ax - cx + cy, by - cy + cx, bx - cx + cy
                w(f'G0 X{f(ax)} Y{f(ay)} F9000')
                e += math.hypot(bx - ax, by - ay) * area / fil_area
                w(f'G1 X{f(bx)} Y{f(by)} E{e:.5f} F2400')
        w('G1 E{:.5f} F2400'.format(e - 0.8)); e -= 0.8  # retract
    w(f'G1 Z{f(lh * layers + 10)} F3000'); w('M104 S0'); w('M140 S0'); w('M84')
    fil_mm = e + 12
    w(f'; filament used [mm] = {fil_mm:.2f}')
    w(f'; filament used [g] = {fil_mm * fil_area * 1.24 / 1000:.2f}')
    w('; estimated printing time (normal mode) = 42m 18s')
    w('; filament_type = PLA')
    return '\n'.join(L) + '\n'

def cnc_sample():
    L = []
    w = L.append
    w('%'); w('O1001 (GCODESCOPE DEMO PLATE)')
    w('(MATERIAL: ALUMINUM 6061, STOCK 100 X 70 X 12)')
    w('G21 G90 G17 G40 G49 G80')
    # T1 contour with rounded corners, 3 step-downs
    w('T1 M06 (10MM FLAT END MILL)'); w('S8000 M03'); w('G54'); w('G43 H01 Z25.'); w('M08')
    R = 8
    x0, y0, x1, y1 = -5, -5, 105, 75
    # lead-in: G41 line + tangent arc, lead-out: tangent arc + G40 line
    w(f'G00 X{x0 - 15} Y{y0 + R - 5}')
    for z in (-3, -6, -9):
        w(f'G00 Z2.'); w(f'G01 Z{z}. F300')
        w(f'G41 D01 G01 X{x0 - 5} Y{y0 + R - 5} F1200')
        w(f'G03 X{x0} Y{y0 + R} I0. J5.')
        w(f'G01 Y{y1 - R}'); w(f'G02 X{x0 + R} Y{y1} I{R} J0.')
        w(f'G01 X{x1 - R}'); w(f'G02 X{x1} Y{y1 - R} I0. J-{R}.')
        w(f'G01 Y{y0 + R}'); w(f'G02 X{x1 - R} Y{y0} I-{R}. J0.')
        w(f'G01 X{x0 + R}'); w(f'G02 X{x0} Y{y0 + R} R{R}.')
        w(f'G03 X{x0 - 5} Y{y0 + R + 5} I-5. J0.')
        w(f'G40 G01 X{x0 - 15}')
        w(f'G00 Y{y0 + R - 5}')
    w('G00 Z25.')
    # circular pocket with helical entry, R50 center 30,35 radius 15
    w('(CIRCULAR POCKET D30)')
    cx, cy = 30, 35
    w(f'G00 X{cx + 3} Y{cy}'); w('G00 Z2.'); w('G01 Z0. F300')
    for i in range(4):
        w(f'G03 X{cx + 3} Y{cy} Z{-1.5 * (i + 1)} I-3. J0. F600')
    for r in (6, 9, 12, 10):
        w(f'G01 X{cx + r} Y{cy} F1000'); w(f'G03 X{cx + r} Y{cy} I-{r}. J0.')
    w('G00 Z25.')
    # slot with arcs
    w('(SLOT)')
    w('G00 X60. Y20.'); w('G00 Z2.'); w('G01 Z-2. F300')
    w('G01 X80. F1000'); w('G03 X80. Y50. R15.'); w('G01 X60.'); w('G03 X60. Y20. R15.')
    w('G00 Z25.'); w('M09'); w('M05')
    # T3 spot drill, T2 peck drill, T4 tap, T1 bore milling
    w('T3 M06 (SPOT DRILL D10 90DEG)'); w('S3000 M03'); w('G43 H03 Z25.'); w('M08')
    w('G00 X5. Y5.')
    w('G99 G81 X5. Y5. Z-1.5 R2. F150')
    w('X95.'); w('Y65.'); w('X5.')
    w('G80'); w('G00 Z25.')
    w('T2 M06 (6.8MM DRILL)'); w('S3500 M03'); w('G43 H02 Z25.'); w('M08')
    w('G00 X5. Y5.')
    w('G98 G83 X5. Y5. Z-14. R2. Q4. F250')
    w('X95.'); w('Y65.'); w('X5.')
    w('G80'); w('G00 Z25.')
    w('T4 M06 (TAP M8X1.25)'); w('S400 M03'); w('G43 H04 Z25.')
    w('M29 S400')
    w('G99 G84 X95. Y5. Z-12. R5. F500')
    w('Y65.')
    w('G80'); w('G00 Z25.')
    w('T1 M06 (10MM FLAT END MILL)'); w('S8000 M03'); w('G43 H01 Z25.')
    w('(BORE MILLING D16)')
    w('G00 X45. Y60.'); w('G00 Z2.'); w('G01 Z0. F300'); w('G01 X48. F800')
    for i in range(1, 5):
        w(f'G03 X48. Y60. Z-{i * 2}. I-3. J0.')
    w('G03 X48. Y60. I-3. J0.'); w('G01 X45.')
    w('G00 Z50.'); w('M09'); w('M05')
    w('G28 G91 Z0.'); w('G90'); w('M30'); w('%')
    return '\n'.join(L) + '\n'

HEIDENHAIN_SAMPLE = """\
0  BEGIN PGM PLATE MM
1  ; GcodeScope demo plate - HEIDENHAIN TNC 640 Klartext
2  BLK FORM 0.1 Z X-5 Y-5 Z-12
3  BLK FORM 0.2  X+105 Y+75 Z+0
4  TOOL CALL "FREZE_D10" Z S8000 F1200
5  L  Z+50 R0 FMAX M3
6  L  X-20 Y+10 R0 FMAX
6  L  Z+2 R0 FMAX
6  Q1 = -3
7  LBL 1
8  L  Z+Q1 R0 F300
9  APPR LCT X-5 Y+10 R5 RL F1200
10 L  Y+75
11 RND R8
12 L  X+105
13 RND R8
14 L  Y-5
15 RND R8
16 L  X-5
17 RND R8
18 L  Y+10
19 DEP LCT X-20 Y+10 R5 R0
20 FN 2: Q1 = +Q1 - +3
21 FN 11: IF +Q1 GT -9.5 GOTO LBL 1
22 L  Z+50 R0 FMAX
23 CYCL DEF 208 BORE MILLING ~
    Q200=+2 ;SET-UP CLEARANCE ~
    Q201=-12 ;DEPTH ~
    Q206=+300 ;FEED RATE FOR PLNGNG ~
    Q334=+1.5 ;PLUNGING DEPTH ~
    Q203=+0 ;SURFACE COORDINATE ~
    Q204=+50 ;2ND SET-UP CLEARANCE ~
    Q335=+24 ;NOMINAL DIAMETER ~
    Q342=+0 ;ROUGHING DIAMETER ~
    Q351=+1 ;CLIMB OR UP-CUT
24 L  X+30 Y+35 R0 FMAX M99
25 TOOL CALL "PUNTA_D10" Z S3000 F200
26 CYCL DEF 240 CENTERING ~
    Q200=+2 ;SET-UP CLEARANCE ~
    Q343=+1 ;SELECT DIA./DEPTH ~
    Q201=-2 ;DEPTH ~
    Q344=+7 ;COUNTERSINK DIAMETER ~
    Q206=+150 ;FEED RATE FOR PLNGNG ~
    Q211=+0.1 ;DWELL TIME AT DEPTH ~
    Q203=+0 ;SURFACE COORDINATE ~
    Q204=+50 ;2ND SET-UP CLEARANCE
27 PATTERN DEF ~
    CIRC1 (X+72 Y+35 D+30 START+45 NUM4 Z+0)
28 CYCL CALL PAT FMAX M13
29 L  X+8 Y+8 R0 FMAX M99
30 L  X+92 Y+62 R0 FMAX M99
31 TOOL CALL "MATKAP_D6.8" Z S3500 F250
32 CYCL DEF 203 UNIVERSAL DRILLING ~
    Q200=+2 ;SET-UP CLEARANCE ~
    Q201=-15 ;DEPTH ~
    Q206=+250 ;FEED RATE FOR PLNGNG ~
    Q202=+6 ;PLUNGING DEPTH ~
    Q210=+0 ;DWELL TIME AT TOP ~
    Q203=+0 ;SURFACE COORDINATE ~
    Q204=+50 ;2ND SET-UP CLEARANCE ~
    Q212=+1 ;DECREMENT ~
    Q213=+0 ;BREAKS ~
    Q205=+3 ;MIN. PLUNGING DEPTH ~
    Q211=+0 ;DWELL TIME AT DEPTH ~
    Q208=+99999 ;RETRACTION FEED RATE ~
    Q256=+0.2 ;DIST FOR CHIP BRKNG
33 CYCL CALL PAT FMAX M13
34 TOOL CALL "KILAVUZ_M8" Z S400
35 CYCL DEF 207 RIGID TAPPING NEW ~
    Q200=+4 ;SET-UP CLEARANCE ~
    Q201=-12 ;DEPTH OF THREAD ~
    Q239=+1.25 ;THREAD PITCH ~
    Q203=+0 ;SURFACE COORDINATE ~
    Q204=+50 ;2ND SET-UP CLEARANCE
36 CYCL CALL PAT FMAX M13
37 TOOL CALL "DIS_FREZE_D6" Z S9000 F500
38 CYCL DEF 262 THREAD MILLING ~
    Q335=+10 ;NOMINAL DIAMETER ~
    Q239=+1.5 ;THREAD PITCH ~
    Q201=-10 ;THREAD DEPTH ~
    Q355=+0 ;THREADS PER STEP ~
    Q253=+750 ;F PRE-POSITIONING ~
    Q351=+1 ;CLIMB OR UP-CUT ~
    Q200=+2 ;SET-UP CLEARANCE ~
    Q203=+0 ;SURFACE COORDINATE ~
    Q204=+50 ;2ND SET-UP CLEARANCE ~
    Q207=+500 ;FEED RATE FOR MILLING ~
    Q512=+0 ;FEED FOR APPROACH
39 L  X+8 Y+8 R0 FMAX M99
40 L  X+92 Y+62 R0 FMAX M99
41 L  Z+100 R0 FMAX M30
42 END PGM PLATE MM
"""

SINUMERIK_SAMPLE = """\
; GcodeScope demo plate - SINUMERIK 840D sl
N10 G17 G90 G54 G71
N20 DEF REAL ZSTEP=3
N30 T="MILL_D10" D1
N40 M6
N50 S8000 M3
N60 G0 X-20 Y10 Z50
N70 R1=-3
N80 PASS: G1 Z=R1 F300
N90 G41 G1 X-5 Y10 F1200
N100 G1 Y67
N110 G2 X3 Y75 CR=8
N120 G1 X97
N130 G2 X105 Y67 CR=8
N140 G1 Y3
N150 G2 X97 Y-5 CR=8
N160 G1 X3
N170 G2 X-5 Y3 CR=8
N180 G1 Y10
N190 G40 G1 X-20 Y10
N200 R1=R1-ZSTEP
N210 IF R1>=-9 GOTOB PASS
N220 G0 Z50
N230 ; helical bore D24
N240 G0 X37 Y35
N250 G0 Z2
N260 G1 Z0 F300
N270 G3 X37 Y35 Z-12 I=AC(30) J=AC(35) TURN=7 F800
N280 G3 X37 Y35 I-7 J0
N290 G1 X30 Y35
N300 G0 Z50
N310 T="SPOT_D10" D1
N320 M6
N330 S3000 M3 F150
N340 MCALL CYCLE81(50,0,2,-2)
N350 HOLES2(72,35,15,45,90,4)
N360 X8 Y8
N370 X92 Y62
N380 MCALL
N390 T="DRILL_D6.8" D1
N400 M6
N410 S3500 M3 F250
N420 MCALL CYCLE83(50,0,2,-15,,,6,1,0,0,1,1)
N430 HOLES2(72,35,15,45,90,4)
N440 MCALL
N450 T="TAP_M8" D1
N460 M6
N470 S400 M3
N480 MCALL CYCLE84(50,0,4,-12,,0,5,8,1.25,0,400,400)
N490 HOLES2(72,35,15,45,90,4)
N500 MCALL
N510 T="THREADMILL_D6" D1
N520 M6
N530 S9000 M3 F500
N540 CYCLE90(50,0,2,-10,,10,8.4,1.5,500,3,0,8,8)
N550 CYCLE90(50,0,2,-10,,10,8.4,1.5,500,3,0,92,62)
N560 G0 Z100
N570 M30
"""

os.makedirs(OUT, exist_ok=True)
open(os.path.join(OUT, 'sample-print.gcode'), 'w').write(print_sample())
open(os.path.join(OUT, 'sample-cnc.nc'), 'w').write(cnc_sample())
def renumber(prog):
    # Klartext block numbers must be sequential; continuation lines ("    Q200=...") have none
    out, n = [], 0
    for line in prog.split('\n'):
        parts = line.split(None, 1)
        if parts and parts[0].isdigit():
            out.append(f'{n:<2} ' + parts[1])
            n += 1
        else:
            out.append(line)
    return '\n'.join(out)

open(os.path.join(OUT, 'sample-heidenhain.h'), 'w').write(renumber(HEIDENHAIN_SAMPLE))
open(os.path.join(OUT, 'sample-sinumerik.mpf'), 'w').write(SINUMERIK_SAMPLE)
print('ok')
